### ISSUE TITLE
What are your thoughts on crypto/web3/blockchain?

### ISSUE THREAD

**Issue by RobotLivermore** [tooniez/ama#1]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/tooniez/)! [I](https://github.com/tooniez/) will try my best to answer to you and help you!

- [x] Check that your question [was not already answered](https://github.com/tooniez/ama/issues?q=is%3Aissue+is%3Aclosed) please.

**Comment by tooniez** [comment]
Hi thanks for your question! I'll spend a few minutes to dive into FinTech from what I understand so far..

First thoughts that come to mind:
- Account Management
- Wallet Management
- Transactions
- Smart Contract Interactions
- Token Capabilitiies
- Exchange Interopperability

In terms of order of risk, I feel this is where I sit atm.
- Compliance (regulations, protocols, token standards)
- Security (encryption, overflows, access)
- Performance (trans volumes, congestion)
- Interoperability (wallet types, cross-chaining)

That coverage should check off reliability, security, performance, interoperability, compliance, for crypto, Web3, and blockchain technologies broadly.
